### ISSUE TITLE
QNX Support Missing (Example Application)

### ISSUE THREAD

**Issue by rameshpasunoori** [mdns-js/node-mdns-js#55]
Hello Team

I try to run simple.js from examples but it's failing in var interfaces = os.networkInterfaces() call

Complete Log:
# DEBUG=mdns:browser:packet node examples/simple.js
premain 123 
In Main() 123 
In uv__platform_loop_init()
/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/lib/networking.js:32
  var interfaces = os.networkInterfaces();
                      ^

Error: Unknown system error 1: Unknown system error 1, uv_interface_addresses
    at Error (native)
    at Networking.start (/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/lib/networking.js:32:23)
    at Networking.startRequest (/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/lib/networking.js:191:8)
    at Networking.addUsage (/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/lib/networking.js:209:8)
    at new module.exports (/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/lib/browser.js:136:14)
    at Object.browserCreated [as createBrowser] (/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/index.js:26:10)
    at Object.<anonymous> (/pas/node-v4.4.3/x86/lib/node_modules/mdns-js/examples/simple.js:10:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

Provide some update on this.

Regards
Ramesh

**Comment by kmpm** [comment]
Is the call to os.networkinterfaces not supported on qnx? 
That method is in the node api and I can't really do much about it and I don't have a qnx system where I could try to find an alternative way of finding those interfaces. 

Could you please test that api call in some other code and see if it works there?

**Comment by kmpm** [comment]
This might be solved with the port5353 branch..
